### 发送验证码
POST {{domain}}/api_v1/system/captcha/send
Content-Type: application/json

{
    "passport" : "{{passport}}",
    "_py_secret" : "{{secret}}"
}

> {%
    client.test("发送验证码", function(){
        client.assert(response.status === 200);
        client.assert(response.body['status'] === 0);
    })
%}

### 获取验证码
POST {{domain}}/api_v1/system/core/helper
Content-Type: application/json

{
    "type": "captcha|{{passport}}",
    "_py_secret": "{{secret}}"
}

> {%
    client.test('获取验证码', ()=>{
        client.assert(response.status === 200)
        client.assert(response.body['status'] === 0)
        client.global.set("_captcha", response.body['data'])
    })
%}

### 验证码登录
POST {{domain}}/api_v1/system/auth/login
Content-Type: application/json
x-type: backend
x-os:{{x-os}}

{
    "passport" : "{{passport}}",
    "captcha" : "{{_captcha}}",
    "_py_secret" : "{{secret}}"
}

> {%
    client.test("验证验证码是否可以登录", function(){
        client.assert(response.status === 200);
        client.assert(response.body['status'] === 0);
    })
%}
