### 登录成功
POST {{domain}}/api_v1/system/auth/access
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "_py_secret" : "{{secret}}"
}

> {%
    client.test("Upload Image Use Type Base64", function(){
        client.assert(response.status === 200);
        client.assert(response.body.status === 0);
    })
%}

### 登录失败
POST {{domain}}/api_v1/system/auth/access
Content-Type: application/json
Authorization: Bearer {{token}}X

{
    "_py_secret" : "{{secret}}"
}
> {%
    client.test("错误的登录信息, 返回401", function(){
        client.assert(response.status === 401);
    })
%}

